# Generated by Django 3.1.7 on 2021-02-24 20:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.TextField(verbose_name='Continent')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField(verbose_name='Date Registered')),
                ('new_cases_smoothed', models.IntegerField(null=0, validators=[django.core.validators.MaxValueValidator(2097151)], verbose_name='New Cases')),
                ('new_deaths_smoothed', models.IntegerField(null=0, validators=[django.core.validators.MaxValueValidator(2097151)], verbose_name='new Deaths')),
                ('new_tests_smoothed', models.IntegerField(null=0, validators=[django.core.validators.MaxValueValidator(2097151)], verbose_name='New Tests')),
                ('new_vaccinations_smoothed', models.IntegerField(null=0, validators=[django.core.validators.MaxValueValidator(2097151)], verbose_name='New Vaccinations')),
                ('total_cases', models.PositiveIntegerField(null=0, verbose_name='Total Cases')),
                ('total_deaths', models.PositiveIntegerField(null=0, verbose_name='Total Deaths')),
                ('total_tests', models.PositiveIntegerField(null=0, verbose_name='Total Tests')),
                ('people_vaccinated', models.BigIntegerField(null=0, verbose_name='People Vaccinated')),
                ('population_density', models.BigIntegerField(null=0, verbose_name='Total Fully Vaccinated')),
                ('population', models.BigIntegerField(null=0, verbose_name='Total Fully Vacinated')),
                ('life_expectancy', models.PositiveIntegerField(null=0, verbose_name='Life Expectancy')),
                ('human_development_index', models.FloatField(verbose_name='Human Development Index (HDI)')),
                ('time_picked', models.DateTimeField(verbose_name='Time Picked Data')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='covidmap.continent')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='covidmap.location')),
            ],
        ),
    ]
