# Generated by Django 3.1.7 on 2021-02-24 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='name', to='covidmap.continent'),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='name', to='covidmap.location'),
        ),
    ]
