# Generated by Django 3.1.7 on 2021-02-24 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidmap', '0002_auto_20210224_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='covidmap.continent'),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='covidmap.location'),
        ),
    ]
